name: "citelang badge action"
description: "Generate a citelang badge (png) for your package"
inputs:
  manager:
    description: the name of the package manager
    required: true
  package:
    description: the name of the package
    required: true
  outfile:
    description: the name of the outputfile (png)
    required: false
    default: ""
  args:
    description: additional arguments / parameters for citelang.
    required: false
    default: ""

runs:
  using: "composite"
  steps:

    - name: Install CiteLang
      shell: bash
      run: which citelang || pip install citelang

    - name: Generate CiteLang
      env:
        manager: ${{ inputs.manager }}
        package: ${{ inputs.package }}
        outfile: ${{ inputs.outfile }}
        args: ${{ inputs.args }}
      run: |
          if [[ "${outfile}" == "" ]]; then
              outfile="${manager}-${package}.png"
          fi
          citelang badge ${manager} ${package} --outfile ${outfile} ${args}
      shell: bash
