name: Release Python Package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Install
      run: conda create --quiet --name citelang twine

    - name: Install dependencies
      run: |
        export PATH="/usr/share/miniconda/bin:$PATH"
        source activate citelang
        pip install -e .[all]
        pip install setuptools wheel twine

    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USER }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASS }}
      run: |
        export PATH="/usr/share/miniconda/bin:$PATH"
        source activate citelang
        python setup.py sdist bdist_wheel
        twine upload dist/*

    - name: Generate CiteLang Credit Markdown
      uses: vsoch/citelang/action/gen@main
      env:
        CITELANG_LIBRARIES_KEY: ${{ secrets.CITELANG_LIBRARIES_KEY }}
      with:
        package: citelang
        manager: pypi
        outfile: software-credit.md
        args: "--min-credit 0.001"

    - name: Generate CiteLang Badge
      uses: vsoch/citelang/action/badge@main
      env:
        CITELANG_LIBRARIES_KEY: ${{ secrets.CITELANG_LIBRARIES_KEY }}
      with:
        package: citelang
        manager: pypi
        outfile: docs/assets/img/pypi-citelang.png
        args: "--min-credit 0.001 --force"

    - name: View generated file
      run: cat software-credit.md

    - name: Push Software Credit and Badge
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@users.noreply.github.com"
        git add software-credit.md docs/assets/img/pypi-citelang.png
        git commit -m "Automated push with new software-credit $(date '+%Y-%m-%d')" || exit 0
        git push origin main || exit 0
