name: test-action

on:
  pull_request: []

jobs:
  test-action:
    name: Test CiteLang
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install CiteLang
        run: pip install -e .[all]

      - name: Clone Repository
        run: git clone https://github.com/singularityhub/singularity-hpc /tmp/shpc

      - name: Test CiteLang Contrib
        uses: ./action/contrib
        with:   
          root: /tmp/shpc
          outdir: /tmp/shpc/.contrib
          start: 0.0.52
          end: 0.0.53
          detail: true

      - name: Ensure cache is populated
        run: tree .contrib/cache

      - name: Test CiteLang Released
        uses: vsoch/citelang/action/gen@main
        env:
          CITELANG_LIBRARIES_KEY: ${{ secrets.CITELANG_LIBRARIES_KEY }}
        with:   
          package: citelang
          manager: pypi
          outfile: software-credit.md

      - name: Test citelang gen      
        uses: ./action/gen
        env:
          CITELANG_LIBRARIES_KEY: ${{ secrets.CITELANG_LIBRARIES_KEY }}
        with:   
          package: citelang
          manager: pypi
          outfile: citelang.md

      - name: View generated file
        run: cat citelang.md
        
      - name: Test citelang badge
        uses: ./action/badge
        env:
          CITELANG_LIBRARIES_KEY: ${{ secrets.CITELANG_LIBRARIES_KEY }}
        with:   
          package: citelang
          manager: pypi
