name: test-action

on:
  pull_request: []

jobs:
  test-action:
    name: Test CiteLang
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install CiteLang
        run: pip install -e .

      - name: Test citelang gen      
        uses: ./action/gen
        with:   
          package: citelang
          manager: pypi
          outfile: citelang.md

      - name: View generated file
        run: cat citelang.md
