name: test-action

on:
  pull_request: []

jobs:
  test-action:
    name: Test CiteLang
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Branch Name
        run: echo branch=${GITHUB_REF##*/} >> $GITHUB_ENV

      - name: Test citelang gen      
        uses: ./action/gen
        with:   
          package: citelang
          manager: pypi
          outfile: citelang.md
          branch: ${{ env.branch }}

      - name: View generated file
        run: cat citelang.md
